{% set name = "bibmon" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bibmon-{{ version }}.tar.gz
  sha256: 2d4768cb935e8bb65bfe616969470b32d0aecfaf6e89d9bd59138578eb8f2279

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools
  run:
    - python >=3.12
    - numpy >=2.1.0
    - scipy >=1.14.1
    - scikit-learn >=1.5.1
    - pandas >=2.2.2
    - matplotlib-base >=3.9.0
    - seaborn >=0.13.2
    - statsmodels >=0.14.1
    - optuna >=3.6.1

test:
  imports:
    - bibmon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petrobras/bibmon
  summary: Library with routines for data-driven process monitoring.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - camaramm
